# Generated by Django 4.0.1 on 2022-02-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figures', '0002_rename_circle_type_circle_ftype'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='image',
            field=models.ImageField(default='Круг.png', upload_to='figures/'),
            preserve_default=False,
        ),
    ]
