# Generated by Django 4.0.1 on 2022-02-04 12:01

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('figures', '0004_alter_circle_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='image',
            field=models.ImageField(default=pathlib.PurePosixPath('media/figures/Круг1.png'), upload_to=pathlib.PurePosixPath('media/figures')),
        ),
    ]
